fix: animate ambient animations based on the game time
toddeTV/zlig pull request #127
Opened 2024-12-05 00:24 UTC by fehnomenal

fix #119

I created a function to allow listening for game time ticks. The callbacks get some info, including a delta for ambient animations.
This delta is calculated based on the game time seconds passed this tick. I just played around with the values which looked nice for the ocean.

2025-01-21 15:57 UTC, toddeTV requested changes
Awesome work 🔥

Only two small questions :)

2025-01-21 15:57 UTC, toddeTV commented on src/composables/useGameTime.ts
> +    if (gameTimeSecondsPassed) {
question: Why is this check needed?

2025-01-21 15:57 UTC, toddeTV commented on src/utils/duration.ts
> +  static fromSeconds(seconds: Big): Duration
question: Why add overloads here when the return is the same? Only for IDE auto-completion and hints or do I miss something?

2025-01-22 15:14 UTC, fehnomenal commented on src/utils/duration.ts
> +  static fromSeconds(seconds: Big): Duration
Hm, you're right. Probably left over from a previous iteration 😅

2025-01-22 15:19 UTC, fehnomenal commented on src/composables/useGameTime.ts
> +    if (gameTimeSecondsPassed) {
Iirc it is an optimization to skip callbacks when the game is paused and no progress would be reported. Pausing works by setting the current factor to zero.

The logic can be made more obvious by checking the factor instead.

2025-01-22 18:17 UTC, fehnomenal commented
I addressed both of your points. Please take another look if you are satisfied :smiley:

2025-01-22 20:05 UTC, toddeTV commented on src/composables/useGameTime.ts
> +    if (gameTimeSecondsPassed) {
That makes perfect sense - I missed that. Thanks for the clarification! 😊

I've just resolved the merge conflicts and removed the redundant duplicate condition check.

2025-01-22 20:07 UTC, merged